apiVersion: v1
kind: Service
metadata:
  name: qm18-metric-prometheus-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9157'
  labels:
    app: mq-metric-prometheus
    app.kubernetes.io/instance: qm1-prometheus-instance
    app.kubernetes.io/name: qm1-prometheus-name
spec:
  ports:
  - name: metrics
    port: 9157
    targetPort: 9157
    protocol: TCP
  selector:
    app: mq-metric-prometheus-app
  type: ClusterIP
